"""Tier D: semantic checks against the stdlib catalog.

The code/unknown-type rule: the base type a piece of code references must be known – it is
either a stdlib symbol (xbsl/data/stdlib.json, generated by tools/extract_stdlib.py), or
a project object (the Имя of a yaml with a ВидЭлемента), or a locally declared type
(структура/перечисление/исключение). Every type position of the module is checked:

- `новый <Type>` – construction;
- `<expression> как <Type>` – a cast;
- the annotation of a declaration/field/catch `знч/пер/поймать <name>: <Type>` (including a
  comma-separated list of names with a shared type – `знч a, b: <Type>`);
- a method signature – the parameter types `(<name>: <Type>, ...)` and the return type `): <Type>`.

A type expression is parsed by its root: for an FQN (`КэшПрайса.СтрокаДанных`) only the
first segment is checked (nested types are not described by the catalog – we leave them alone
to avoid false positives); the nullable suffix `?` is ignored; for a generic
(`Массив<СотрудникJSON>`) both the base and each argument are checked. The namespace roots
(Справочник/Документ/...) are present in the catalog, so an FQN like `Справочник.Товары.Ссылка`
resolves by its root.

The rule is project-wide (cross-file): it is correct only with the whole project known (the
objects and local types of all modules), so in single-file mode (lint_source) it does not run
– this rules out false positives. Verified on the real corpus: 0 false positives.

The code/unknown-object-type rule goes one segment deeper: when the FQN root is a project
object, the second segment must belong to the family of types generated by that object –
a built-in derived type ("Типы, порождаемые элементом проекта" in the platform docs: Ссылка,
Объект, Данные, Запись, НаборЗаписей, the keys, the write/delete parameters...), a tabular
section from the object's yaml, or a structure/enumeration/exception declared in the object's
modules (`<Имя>.xbsl`, `<Имя>.<Часть>.xbsl`). The built-in list is a single union across the
object kinds rather than a per-kind table: a suffix valid for another kind passes (a false
negative), which keeps the rule free of false positives. Objects of kinds outside the checked
set are skipped entirely, as are namespace-qualified references (`Справочник.Имя.Ссылка`) –
the real corpus does not use this form, and objects supplied by external libraries would make
the check guess. Deeper segments (`НаборЗаписей.Данные`, nested report parameters) are not
checked.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from functools import lru_cache

from xbsl import dataset, i18n
from xbsl.diagnostics import Diagnostic, Severity
from xbsl.engine import SourceFile, rule
from xbsl.lexer import tokens
from xbsl.rules._syntax import code_tokens
from xbsl.rules.yaml_schema import _HAVE_YAML, _parsed

MESSAGES = {
    "code/unknown-type.title": {
        "ru": "Неизвестный тип",
        "en": "Unknown type",
    },
    "code/unknown-type.unknown": {
        "ru": "Неизвестный тип '{name}' – нет ни в stdlib, ни среди объектов проекта или локальных типов.",
        "en": "Unknown type '{name}' – not in stdlib, nor among the project objects or local types.",
    },
    "code/unknown-object-type.title": {
        "ru": "Неизвестный тип объекта проекта",
        "en": "Unknown project-object type",
    },
    "code/unknown-object-type.unknown": {
        "ru": "Неизвестный тип '{name}' – у объекта '{root}' ({kind}) нет производного типа, "
              "табличной части или структуры модуля с именем '{seg}'.",
        "en": "Unknown type '{name}' – object '{root}' ({kind}) has no derived type, "
              "tabular section or module structure named '{seg}'.",
    },
}
i18n.register(MESSAGES)

_LOCAL_TYPE_KW = ("STRUCTURE", "ENUMERATION", "EXCEPTION")


@lru_cache(maxsize=1)
def _stdlib_names() -> frozenset[str]:
    try:
        return frozenset(dataset.load_json("stdlib.json")["names"])
    except (dataset.DatasetError, KeyError, ValueError):
        return frozenset()


# The object name for _project_object_names comes from regexes, not a full yaml parse:
# in the whole-project profile yaml.load of every description for the sake of two
# top-level fields was the most expensive line (the PyYAML constructor stays pure
# Python even with libyaml).
# The yaml of the platform is bilingual: shipped code carries English keys too
# (ElementKind/Name in БизКуб), so both spellings are recognized.
_TOP_KIND_RE = re.compile(r"^(?:ВидЭлемента|ElementKind):", re.M)
_TOP_NAME_RE = re.compile(r"^(?:Имя|Name):[ \t]*(['\"]?)([^\r\n#]*?)\1[ \t]*(?:#.*)?\r?$", re.M)
_MISSING = object()


def _object_name_fast(s: SourceFile) -> str | None:
    """The metadata-object name (a file with ВидЭлемента) without a full yaml parse, cached."""
    cached = s.cache.get("object_name_fast", _MISSING)
    if cached is not _MISSING:
        return cached
    name = None
    if _TOP_KIND_RE.search(s.text):
        m = _TOP_NAME_RE.search(s.text)
        if m and m.group(2):
            name = m.group(2)
    s.cache["object_name_fast"] = name
    return name


def _project_object_names(sources: list[SourceFile]) -> set[str]:
    names: set[str] = set()
    for s in sources:
        if s.kind != "yaml":
            continue
        nm = _object_name_fast(s)
        if nm is not None:
            names.add(nm)
    return names


def _file_local_type_decls(s: SourceFile) -> list[tuple[str, int]]:
    """The structures/enumerations/exceptions declared in one module, as (name, line) pairs.

    The position side of _file_local_types – kept separate so the rules keep their set-based
    signature while the project index (xbsl.indexer) gets the declaration lines.
    """
    cached = s.cache.get("local_type_decls")
    if cached is not None:
        return cached
    decls: list[tuple[str, int]] = []
    toks = tokens(s)
    for i, t in enumerate(toks):
        if t.kind == "KEYWORD" and t.value[:1].islower() and t.canonical in _LOCAL_TYPE_KW:
            for j in range(i + 1, min(i + 3, len(toks))):
                if toks[j].kind == "IDENT":
                    decls.append((toks[j].value, toks[j].line))
                    break
    # Cached: several project rules need the declarations - without the cache the token
    # loop repeated per rule (visible in the whole-project profile).
    s.cache["local_type_decls"] = decls
    return decls


def _file_local_types(s: SourceFile) -> set[str]:
    """Names of the structures/enumerations/exceptions declared in one module."""
    return {name for name, _ in _file_local_type_decls(s)}


def _local_type_names(sources: list[SourceFile]) -> set[str]:
    names: set[str] = set()
    for s in sources:
        if s.kind == "xbsl":
            names |= _file_local_types(s)
    return names


# Derived types generated by a project object – a single union across the object kinds
# (docs: "Типы, порождаемые элементом проекта"). The versioned catalog carries the full
# per-kind sets extracted from the distribution docs (stdlib.json object_members); this
# built-in union is the safety net for data generated before that key existed and for
# members the template pages do not describe (ПараметрыЗаполнения). A suffix of another
# kind passes as a false negative; the union keeps the rule free of false positives.
_MEMBER_TYPE_TAILS = frozenset({
    "Ссылка", "Объект", "Данные", "Запись", "НаборЗаписей",
    "КлючЗаписи", "КлючОсновногоФильтра", "КлючРазрешенийИзмерений",
    "ДанныеРасчетаРазрешений",
    "ПараметрыЗаписи", "ПараметрыУдаления", "ПараметрыЗаполнения",
    "Параметры",
    "АвтоматическаяФормаСписка", "АвтоматическаяФормаОбъекта", "АвтоматическаяФормаЗаписи",
})

# Object kinds whose generated type family is known. The catalog's object_members adds
# kinds on top; kinds outside the resulting set are skipped. Structure-only kinds
# (ОбщийМодуль, HttpСервис) generate no member types but carry module-declared ones.
_BASE_CHECKED_KINDS = frozenset({
    "Справочник", "Документ", "РегистрСведений", "РегистрНакопления",
    "Перечисление", "ОбщийМодуль", "КомпонентИнтерфейса",
    "ПараметрыРаботыКлиента", "HttpСервис", "КлючДоступа", "ПланОбмена",
})


@lru_cache(maxsize=1)
def _object_members() -> dict[str, frozenset[str]]:
    """Per-kind generated member names from the versioned catalog ({} when absent)."""
    try:
        raw = dataset.load_json("stdlib.json").get("object_members") or {}
    except (dataset.DatasetError, KeyError, ValueError):
        return {}
    return {k: frozenset(v) for k, v in raw.items() if isinstance(v, list)}


def _checked_kinds() -> frozenset[str]:
    return _BASE_CHECKED_KINDS | frozenset(_object_members())


def _member_family(kind: str) -> frozenset[str]:
    """Built-in members generated for objects of the kind: catalog data + the safety net."""
    return _object_members().get(kind, frozenset()) | _MEMBER_TYPE_TAILS


def _row_type_names(node) -> set[str]:
    """Type names a yaml declares for itself: the row type of a dynamic list.

    A form's dynamic list names its generated row type with `ИмяТипаДанныхСтроки:
    ДанныеСтрокиСписка` (docs topics/virtual-table, topics/accumulation-register-example),
    and the type is then referenced as `<ИмяФормы>.<это имя>` - in the form's own yaml and
    in its module. Such a name is not in the kind's fixed member family: it is invented in
    the yaml, so it has to be collected from the tree.
    """
    names: set[str] = set()
    if isinstance(node, dict):
        value = node.get("ИмяТипаДанныхСтроки")
        if isinstance(value, str) and value:
            names.add(value)
        for v in node.values():
            names |= _row_type_names(v)
    elif isinstance(node, list):
        for item in node:
            names |= _row_type_names(item)
    return names


def _project_object_info(sources: list[SourceFile]) -> dict[str, dict]:
    """Per project object: the kind and the member-type names it generates.

    Members are the tabular sections from the object's yaml plus the local types declared
    in the object's modules – the files `<Имя>.xbsl` and `<Имя>.<Часть>.xbsl` (the module
    file is matched to its object by name, per the yaml/name-matches-file invariant).
    """
    info: dict[str, dict] = {}
    if not _HAVE_YAML:
        return info
    for s in sources:
        if s.kind != "yaml":
            continue
        data, err = _parsed(s)
        if err is not None or not isinstance(data, dict) or not data.get("ВидЭлемента"):
            continue
        nm = data.get("Имя")
        if not isinstance(nm, str):
            continue
        members: set[str] = set(_row_type_names(data))
        parts = data.get("ТабличныеЧасти")
        if isinstance(parts, list):
            for p in parts:
                if isinstance(p, dict) and isinstance(p.get("Имя"), str):
                    members.add(p["Имя"])
        info[nm] = {"kind": data["ВидЭлемента"], "members": members}
    for s in sources:
        if s.kind != "xbsl":
            continue
        owner = s.path.name[: -len(".xbsl")].split(".", 1)[0]
        rec = info.get(owner)
        if rec is not None:
            rec["members"] |= _file_local_types(s)
    return info


# --- Parsing type expressions over tokens --------------------------------------------

def _next(toks: list, k: int) -> int:
    """Index of the nearest non-comment token starting at k (may return len when exhausted)."""
    n = len(toks)
    while k < n and toks[k].kind == "COMMENT":
        k += 1
    return k


def _type_chains(toks: list, start: int) -> tuple[list[list], int]:
    """The dotted name chains of a type expression from position start, and the index past its end.

    A chain starts at the IDENT opening the expression, the base of a generic or the start of
    each argument (after `<` or `,`); the FQN tail (after `.`) extends the current chain. If the
    expression does not start with an IDENT (e.g. the keyword `неизвестно` or a bracket) – there
    are no chains.
    """
    chains: list[list] = []
    depth = 0
    prev: str | None = None  # None | '<' | ',' | '.' | 'ident'
    extendable = False  # a `.` after the current position extends the last chain
    i, n = start, len(toks)
    while i < n:
        t = toks[i]
        if t.kind == "COMMENT":
            i += 1
            continue
        if t.kind == "IDENT":
            if prev in (None, "<", ","):
                chains.append([t])
                extendable = True
            elif prev == "." and extendable and chains:
                chains[-1].append(t)
            else:
                extendable = False
            prev = "ident"
            i += 1
            continue
        if t.kind == "OP":
            v = t.value
            if v == ".":
                prev = "."
                i += 1
                continue
            if v == "<":
                depth += 1
                prev = "<"
                extendable = False
                i += 1
                continue
            if v == ">":
                if depth == 0:
                    break
                depth -= 1
                prev = "ident"
                extendable = False  # `Массив<Число>.Х` does not extend the argument chain
                i += 1
                continue
            if v == ",":
                if depth == 0:
                    break
                prev = ","
                extendable = False
                i += 1
                continue
            if v == "?":  # nullable suffix – does not affect parsing
                prev = "ident"
                extendable = False
                i += 1
                continue
        break
    return chains, i


def _type_roots(toks: list, start: int) -> tuple[list, int]:
    """The root type names of a type expression – the first token of each chain."""
    chains, end = _type_chains(toks, start)
    return [c[0] for c in chains], end


def _annotation_start(toks: list, j: int) -> int | None:
    """From the position of the first name in a declaration/catch, return the type start after `:`.

    Supports a comma-separated list of names with a shared type (`знч a, b: Тип`) and the single
    form (`пер x: Тип`, `поймать Ошибка: Тип`). If there is no type annotation – None.
    """
    n = len(toks)
    while j < n and toks[j].kind == "IDENT":
        k = _next(toks, j + 1)
        if k < n and toks[k].kind == "OP" and toks[k].value == ",":
            j = _next(toks, k + 1)
            continue
        if k < n and toks[k].kind == "OP" and toks[k].value == ":":
            return _next(toks, k + 1)
        return None
    return None


def _signature_type_starts(toks: list, i: int) -> list[int]:
    """The starts of type expressions in a method/constructor signature, from the keyword index:
    the parameter types and the return type. The parameter list is balanced by parentheses;
    inside parameter types the generics (`<...>`) are swallowed by _type_roots, so a comma inside
    `Соответствие<Строка, Число>` is not confused with a parameter separator."""
    n = len(toks)
    j = _next(toks, i + 1)  # the method name
    if j >= n or toks[j].kind != "IDENT":
        return []
    p = _next(toks, j + 1)  # '(' expected
    if p >= n or not (toks[p].kind == "OP" and toks[p].value == "("):
        return []

    starts: list[int] = []
    depth = 1
    expect_name = True  # start of a parameter (after '(' or ',' at the top level)
    k = p + 1
    while k < n and depth > 0:
        t = toks[k]
        if t.kind == "COMMENT":
            k += 1
            continue
        if t.kind == "OP" and t.value in "([{":
            depth += 1
            expect_name = False
            k += 1
            continue
        if t.kind == "OP" and t.value in ")]}":
            depth -= 1
            k += 1
            continue
        if depth == 1 and expect_name and t.kind == "IDENT":
            c = _next(toks, k + 1)
            if c < n and toks[c].kind == "OP" and toks[c].value == ":":
                s = _next(toks, c + 1)
                starts.append(s)
                _, end = _type_roots(toks, s)
                k = end
                expect_name = False
                continue
            k += 1
            continue
        if depth == 1 and t.kind == "OP" and t.value == ",":
            expect_name = True
            k += 1
            continue
        k += 1

    # the return type: right after the closing ')' of the parameter list
    r = _next(toks, k)
    if r < n and toks[r].kind == "OP" and toks[r].value == ":":
        starts.append(_next(toks, r + 1))
    return starts


def _type_ref_starts(toks: list) -> list[int]:
    """The start indices of all type expressions of the module (by anchor constructs)."""
    starts: list[int] = []
    n = len(toks)
    for i, t in enumerate(toks):
        if t.kind != "KEYWORD" or not t.value[:1].islower():
            continue
        c = t.canonical
        if c in ("NEW", "AS"):
            starts.append(_next(toks, i + 1))
        elif c in ("VAL", "VAR", "CATCH"):
            s = _annotation_start(toks, _next(toks, i + 1))
            if s is not None:
                starts.append(s)
        elif c in ("METHOD", "CONSTRUCTOR"):
            starts.extend(_signature_type_starts(toks, i))
    return starts


def _type_token_facts(s: SourceFile) -> tuple[list, list]:
    """(roots, two-segment chains) of every type position in a module - the shared
    token sweep of the two type rules, cached per file for their mappers."""
    cached = s.cache.get("type_token_facts")
    if cached is not None:
        return cached
    roots: list[tuple[str, int, int]] = []
    chains2: list[tuple[str, str, int, int]] = []
    # Over code_tokens, not the raw ones: inside `Запрос{...}` the anchor words belong to the
    # query language, where `КАК` names a column alias rather than casts to a type
    # (`Количество(Идентификатор) как Количество`).
    toks = code_tokens(s)
    for start in _type_ref_starts(toks):
        chains, _ = _type_chains(toks, start)
        for chain in chains:
            r = chain[0]
            roots.append((r.value, r.line, r.col))
            if len(chain) >= 2:
                seg = chain[1]
                chains2.append((r.value, seg.value, seg.line, seg.col))
    facts = (roots, chains2)
    s.cache["type_token_facts"] = facts
    return facts


def _unknown_type_mapper(source: SourceFile) -> dict | None:
    """The map phase: a yaml contributes its object name, an xbsl its local types and
    the type roots unknown to the stdlib (the project names settle in the reduce)."""
    if source.kind == "yaml":
        nm = _object_name_fast(source)
        return {"k": "y", "name": nm} if nm else None
    if source.kind != "xbsl":
        return None
    stdlib = _stdlib_names()
    if not stdlib:
        return None  # the catalog is not generated – skip the check
    roots, _chains2 = _type_token_facts(source)
    cands = [(v, line, col) for v, line, col in roots if v not in stdlib]
    local = _file_local_types(source)
    if not cands and not local:
        return None
    return {"k": "x", "cands": cands, "local_types": sorted(local)}


@rule(
    "code/unknown-type", "code/unknown-type.title", "D",
    scope="project", severity=Severity.WARNING, mapper=_unknown_type_mapper,
)
def unknown_type(facts: dict[str, dict]) -> Iterable[Diagnostic]:
    known: set[str] = set()
    for fact in facts.values():
        if fact["k"] == "y":
            known.add(fact["name"])
        else:
            known.update(fact["local_types"])
    for rel, fact in facts.items():
        if fact["k"] != "x":
            continue
        for value, line, col in fact["cands"]:
            if value not in known:
                yield Diagnostic(
                    rel, line, col, "code/unknown-type", Severity.WARNING,
                    i18n.t("code/unknown-type.unknown", name=value),
                )


def _object_type_mapper(source: SourceFile) -> dict | None:
    """The map phase: a yaml contributes its object record, an xbsl its local types
    (by owner) and the two-segment type chains - the reduce owns the object model."""
    if source.kind == "yaml":
        data, err = _parsed(source)
        if err is not None or not isinstance(data, dict) or not data.get("ВидЭлемента"):
            return None
        nm = data.get("Имя")
        if not isinstance(nm, str):
            return None
        members = sorted(_row_type_names(data))
        parts = data.get("ТабличныеЧасти")
        if isinstance(parts, list):
            members += [
                p["Имя"] for p in parts
                if isinstance(p, dict) and isinstance(p.get("Имя"), str)
            ]
        return {"k": "y", "name": nm, "kind": data["ВидЭлемента"], "tab_members": members}
    if source.kind != "xbsl":
        return None
    _roots, chains2 = _type_token_facts(source)
    local = _file_local_types(source)
    if not chains2 and not local:
        return None
    owner = source.path.name[: -len(".xbsl")].split(".", 1)[0]
    return {"k": "x", "owner": owner, "local_types": sorted(local), "chains2": chains2}


@rule(
    "code/unknown-object-type", "code/unknown-object-type.title", "D",
    scope="project", severity=Severity.WARNING, mapper=_object_type_mapper,
)
def unknown_object_type(facts: dict[str, dict]) -> Iterable[Diagnostic]:
    objects: dict[str, dict] = {}
    for fact in facts.values():
        if fact["k"] == "y":
            objects[fact["name"]] = {
                "kind": fact["kind"], "members": set(fact["tab_members"]),
            }
    if not objects:
        return
    for fact in facts.values():
        if fact["k"] == "x":
            rec = objects.get(fact["owner"])
            if rec is not None:
                rec["members"].update(fact["local_types"])
    checked = _checked_kinds()
    for rel, fact in facts.items():
        if fact["k"] != "x":
            continue
        for root, seg, line, col in fact["chains2"]:
            rec = objects.get(root)
            if rec is None or rec["kind"] not in checked:
                continue
            if seg in _member_family(rec["kind"]) or seg in rec["members"]:
                continue
            yield Diagnostic(
                rel, line, col, "code/unknown-object-type", Severity.WARNING,
                i18n.t(
                    "code/unknown-object-type.unknown",
                    name=f"{root}.{seg}", root=root, kind=rec["kind"], seg=seg,
                ),
            )
