Ид: ffeacdec-02d6-4f08-bcfa-be89e9a1861a
РежимСовместимости: 9.0
Поставщик: acme
Имя: tasks
Версия: 1.0
Представление: "Tasks (demo)"
ПредставлениеПоставщика: "acme"
ЯзыкиЛокализации: [Русский]
ЯзыкПоУмолчанию: Русский
ЯзыкРазработки: Русский
