ВидЭлемента: Справочник
Ид: 42073842-db14-41d6-a17a-7b03a5d57933
Имя: Задача
ОбластьВидимости: ВПроекте
Интерфейс:
    Объект:
        Форма: КарточкаЗадачи
Реквизиты:
    -
        Имя: Наименование
        Длина: 250
    -
        Ид: 54c9050e-3377-4a67-8c34-c80d1074edfc
        Имя: Срок
        Тип: Дата
    -
        Ид: 771ad094-7290-4156-a847-726ac8f60789
        Имя: Описание
        Тип: Строка
        Многострочная: Истина
    -
        Ид: cb4f3e7f-10a1-4bd9-af5c-9951cc33b918
        Имя: Важность
        Тип: Число
    -
        Ид: f5b5ded8-eb69-4244-b31a-e5d1dd8d3933
        Имя: Выполнена
        Тип: Булево
ТабличныеЧасти:
    -
        Ид: b54d2067-069e-43d4-abae-ad0f6de8c9c8
        Имя: Шаги
        Реквизиты:
            -
                Ид: eb95cb2a-644c-4cf5-bd43-fc79abd32b25
                Имя: Шаг
                Тип: Строка
            -
                Ид: 1b2163db-ee5e-419c-a089-6eb6cd120fe8
                Имя: Готово
                Тип: Булево
