"""Tier D: semantic checks against the stdlib catalog.

The code/unknown-type rule: the base type a piece of code references must be known – it is
either a stdlib symbol (xbsllint/data/stdlib.json, generated by tools/extract_stdlib.py), or
a project object (the Имя of a yaml with a ВидЭлемента), or a locally declared type
(структура/перечисление/исключение). Every type position of the module is checked:

- `новый <Type>` – construction;
- `<expression> как <Type>` – a cast;
- the annotation of a declaration/field/catch `знч/пер/поймать <name>: <Type>` (including a
  comma-separated list of names with a shared type – `знч a, b: <Type>`);
- a method signature – the parameter types `(<name>: <Type>, ...)` and the return type `): <Type>`.

A type expression is parsed by its root: for an FQN (`КэшДанныхСервиса.СтрокаКопии`) only the
first segment is checked (nested types are not described by the catalog – we leave them alone
to avoid false positives); the nullable suffix `?` is ignored; for a generic
(`Массив<ОрганизацияJSON>`) both the base and each argument are checked. The namespace roots
(Справочник/Документ/...) are present in the catalog, so an FQN like `Справочник.Товары.Ссылка`
resolves by its root.

The rule is project-wide (cross-file): it is correct only with the whole project known (the
objects and local types of all modules), so in single-file mode (lint_source) it does not run
– this rules out false positives. Verified on the real corpus: 0 false positives.
"""

from __future__ import annotations

from collections.abc import Iterable
from functools import lru_cache

from xbsllint import dataset, i18n
from xbsllint.diagnostics import Diagnostic, Severity
from xbsllint.engine import SourceFile, rule
from xbsllint.lexer import tokens
from xbsllint.rules.yaml_schema import _HAVE_YAML, _parsed

MESSAGES = {
    "code/unknown-type.title": {
        "ru": "Неизвестный тип",
        "en": "Unknown type",
    },
    "code/unknown-type.unknown": {
        "ru": "Неизвестный тип '{name}' – нет ни в stdlib, ни среди объектов проекта или локальных типов.",
        "en": "Unknown type '{name}' – not in stdlib, nor among the project objects or local types.",
    },
}
i18n.register(MESSAGES)

_LOCAL_TYPE_KW = ("STRUCTURE", "ENUMERATION", "EXCEPTION")


@lru_cache(maxsize=1)
def _stdlib_names() -> frozenset[str]:
    try:
        return frozenset(dataset.load_json("stdlib.json")["names"])
    except (dataset.DatasetError, KeyError, ValueError):
        return frozenset()


def _project_object_names(sources: list[SourceFile]) -> set[str]:
    names: set[str] = set()
    if not _HAVE_YAML:
        return names
    for s in sources:
        if s.kind != "yaml":
            continue
        data, err = _parsed(s)
        if err is None and isinstance(data, dict) and data.get("ВидЭлемента"):
            nm = data.get("Имя")
            if isinstance(nm, str):
                names.add(nm)
    return names


def _local_type_names(sources: list[SourceFile]) -> set[str]:
    names: set[str] = set()
    for s in sources:
        if s.kind != "xbsl":
            continue
        toks = tokens(s)
        for i, t in enumerate(toks):
            if t.kind == "KEYWORD" and t.value[:1].islower() and t.canonical in _LOCAL_TYPE_KW:
                for j in range(i + 1, min(i + 3, len(toks))):
                    if toks[j].kind == "IDENT":
                        names.add(toks[j].value)
                        break
    return names


# --- Parsing type expressions over tokens --------------------------------------------

def _next(toks: list, k: int) -> int:
    """Index of the nearest non-comment token starting at k (may return len when exhausted)."""
    n = len(toks)
    while k < n and toks[k].kind == "COMMENT":
        k += 1
    return k


def _type_roots(toks: list, start: int) -> tuple[list, int]:
    """The root type names of a type expression from position start, and the index past its end.

    A root is the IDENT at the start of the expression, the base of a generic and the start of
    each argument (after `<` or `,`). The FQN tail (after `.`) is not a root. If the expression
    does not start with an IDENT (e.g. the keyword `неизвестно` or a bracket) – there are no roots.
    """
    roots: list = []
    depth = 0
    prev: str | None = None  # None | '<' | ',' | '.' | 'ident'
    i, n = start, len(toks)
    while i < n:
        t = toks[i]
        if t.kind == "COMMENT":
            i += 1
            continue
        if t.kind == "IDENT":
            if prev in (None, "<", ","):
                roots.append(t)
            prev = "ident"
            i += 1
            continue
        if t.kind == "OP":
            v = t.value
            if v == ".":
                prev = "."
                i += 1
                continue
            if v == "<":
                depth += 1
                prev = "<"
                i += 1
                continue
            if v == ">":
                if depth == 0:
                    break
                depth -= 1
                prev = "ident"
                i += 1
                continue
            if v == ",":
                if depth == 0:
                    break
                prev = ","
                i += 1
                continue
            if v == "?":  # nullable suffix – does not affect parsing
                prev = "ident"
                i += 1
                continue
        break
    return roots, i


def _annotation_start(toks: list, j: int) -> int | None:
    """From the position of the first name in a declaration/catch, return the type start after `:`.

    Supports a comma-separated list of names with a shared type (`знч a, b: Тип`) and the single
    form (`пер x: Тип`, `поймать Ошибка: Тип`). If there is no type annotation – None.
    """
    n = len(toks)
    while j < n and toks[j].kind == "IDENT":
        k = _next(toks, j + 1)
        if k < n and toks[k].kind == "OP" and toks[k].value == ",":
            j = _next(toks, k + 1)
            continue
        if k < n and toks[k].kind == "OP" and toks[k].value == ":":
            return _next(toks, k + 1)
        return None
    return None


def _signature_type_starts(toks: list, i: int) -> list[int]:
    """The starts of type expressions in a method/constructor signature, from the keyword index:
    the parameter types and the return type. The parameter list is balanced by parentheses;
    inside parameter types the generics (`<...>`) are swallowed by _type_roots, so a comma inside
    `Соответствие<Строка, Число>` is not confused with a parameter separator."""
    n = len(toks)
    j = _next(toks, i + 1)  # the method name
    if j >= n or toks[j].kind != "IDENT":
        return []
    p = _next(toks, j + 1)  # '(' expected
    if p >= n or not (toks[p].kind == "OP" and toks[p].value == "("):
        return []

    starts: list[int] = []
    depth = 1
    expect_name = True  # start of a parameter (after '(' or ',' at the top level)
    k = p + 1
    while k < n and depth > 0:
        t = toks[k]
        if t.kind == "COMMENT":
            k += 1
            continue
        if t.kind == "OP" and t.value in "([{":
            depth += 1
            expect_name = False
            k += 1
            continue
        if t.kind == "OP" and t.value in ")]}":
            depth -= 1
            k += 1
            continue
        if depth == 1 and expect_name and t.kind == "IDENT":
            c = _next(toks, k + 1)
            if c < n and toks[c].kind == "OP" and toks[c].value == ":":
                s = _next(toks, c + 1)
                starts.append(s)
                _, end = _type_roots(toks, s)
                k = end
                expect_name = False
                continue
            k += 1
            continue
        if depth == 1 and t.kind == "OP" and t.value == ",":
            expect_name = True
            k += 1
            continue
        k += 1

    # the return type: right after the closing ')' of the parameter list
    r = _next(toks, k)
    if r < n and toks[r].kind == "OP" and toks[r].value == ":":
        starts.append(_next(toks, r + 1))
    return starts


def _type_ref_starts(toks: list) -> list[int]:
    """The start indices of all type expressions of the module (by anchor constructs)."""
    starts: list[int] = []
    n = len(toks)
    for i, t in enumerate(toks):
        if t.kind != "KEYWORD" or not t.value[:1].islower():
            continue
        c = t.canonical
        if c in ("NEW", "AS"):
            starts.append(_next(toks, i + 1))
        elif c in ("VAL", "VAR", "CATCH"):
            s = _annotation_start(toks, _next(toks, i + 1))
            if s is not None:
                starts.append(s)
        elif c in ("METHOD", "CONSTRUCTOR"):
            starts.extend(_signature_type_starts(toks, i))
    return starts


@rule(
    "code/unknown-type", "code/unknown-type.title", "D",
    scope="project", severity=Severity.WARNING,
)
def unknown_type(sources: list[SourceFile]) -> Iterable[Diagnostic]:
    stdlib = _stdlib_names()
    if not stdlib:
        return []  # the catalog is not generated – skip the check
    known = set(stdlib) | _project_object_names(sources) | _local_type_names(sources)

    diags: list[Diagnostic] = []
    for s in sources:
        if s.kind != "xbsl":
            continue
        toks = tokens(s)
        for start in _type_ref_starts(toks):
            roots, _ = _type_roots(toks, start)
            for r in roots:
                if r.value not in known:
                    diags.append(Diagnostic(
                        s.rel, r.line, r.col, "code/unknown-type",
                        Severity.WARNING,
                        i18n.t("code/unknown-type.unknown", name=r.value),
                    ))
    return diags
