"""Runtime access to the interface component ui schema (uischema.json).

The schema is generated by tools/extract_uischema.py from the documentation dataset and
lives next to stdlib.json (see xbsl/dataset.py). It feeds the visual designer: the
component palette and the typed properties panel. The response shapes for the LSP
(`xbsl/uiSchema`) and the MCP (`ui_schema`) are built here so the two surfaces stay
identical:

- catalog(): the palette catalog - every component with its package, abstract flag and
  doc snippet, WITHOUT the property lists (compact; a component's full schema is a
  separate request);
- component(name): the full record of one component (properties with type unions, enum
  values, event signatures, slot flags); an unknown name yields close_matches instead;
- both return {"available": False} when the dataset has no ui schema (e.g. a public
  checkout without generated data) - the docsAvailable degradation pattern.

Optional fields of the schema records (abstract, since, doc, nullable, slot, enum,
default, readonly, conflicts) are omitted when false/unknown - consumers treat an
absent key as false/null. See tools/extract_uischema.py for the full data shape.
"""

from __future__ import annotations

import difflib

from xbsl import dataset

#: Keys of a component record served by the catalog (props stay out - the palette
#: does not need them, and the full record is one more request away).
_CATALOG_KEYS = ("package", "abstract", "since", "doc", "conflicts")


def available(version: str | None = None) -> bool:
    """Whether the ui schema has been generated for the data version."""
    return dataset.has_data_file(dataset.UI_SCHEMA_FILE, version)


def catalog(version: str | None = None) -> dict:
    """The palette catalog: components without property lists, or {"available": False}."""
    schema = dataset.load_ui_schema(version)
    if schema is None:
        return {"available": False}
    components = {
        name: {k: rec[k] for k in _CATALOG_KEYS if k in rec}
        for name, rec in (schema.get("components") or {}).items()
    }
    return {
        "available": True,
        "version": (schema.get("meta") or {}).get("element_version"),
        "components": components,
    }


def component(name: str, version: str | None = None) -> dict:
    """The full schema of one component, or close matches for an unknown name.

    {"available": True, "component": {"name": ..., ...record...}} on a hit;
    {"available": True, "component": None, "close_matches": [...]} on a miss;
    {"available": False} when the dataset has no ui schema.
    """
    schema = dataset.load_ui_schema(version)
    if schema is None:
        return {"available": False}
    components = schema.get("components") or {}
    rec = components.get(name)
    if rec is None:
        return {
            "available": True,
            "component": None,
            "close_matches": difflib.get_close_matches(name, components, n=5, cutoff=0.6),
        }
    return {"available": True, "component": {"name": name, **rec}}
